---
- name: "Install PWServer files"
  hosts: localhost

  tasks:
    - name: "Extract PWServer"
      become: true
      unarchive:
        src: ./files/PWServer.zip
        dest: /

    - name: "Extract pwAdmin"
      become: true
      unarchive:
        src: ./files/pwAdmin.zip
        dest: /opt/apache-tomcat-9.0.64/webapps/

    - name: "Remove index.html"
      become: true
      file:
        path: /var/www/html/index.html
        state: absent

    - name: "Extract htdocs"
      become: true
      unarchive:
        src: ./files/htdocs.zip
        dest: /var/www/html

    - name: "Extract lib"
      become: true
      unarchive:
        src: ./files/lib.zip
        dest: /lib/

    - name: "Extract lib32"
      become: true
      unarchive:
        src: ./files/lib32.zip
        dest: /lib32/

    - name: create a new database  
      become: true
      mysql_db: 
        name: dbo 
        state: present 
        login_user: root
        login_password: root

    - name: Restore database
      become: true
      mysql_db:
        name: dbo
        state: import
        target: ./files/dbo.sql
        login_user: root
        login_password: root